<?xml version = "1.0" ?>
<?xml:stylesheet type="text/xsl" href="SystemBOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Address1 CDATA #IMPLIED>
  <!ATTLIST ROW Address2 CDATA #IMPLIED>
  <!ATTLIST ROW Address3 CDATA #IMPLIED>
  <!ATTLIST ROW Address4 CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy CDATA #IMPLIED>
  <!ATTLIST ROW Author CDATA #IMPLIED>
  <!ATTLIST ROW CheckedBy CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW CompanyName CDATA #IMPLIED>
  <!ATTLIST ROW Component_Kind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentKind CDATA #IMPLIED>
  <!ATTLIST ROW CurrentDate CDATA #IMPLIED>
  <!ATTLIST ROW CurrentTime CDATA #IMPLIED>
  <!ATTLIST ROW Date CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW DesignItemId CDATA #IMPLIED>
  <!ATTLIST ROW Document CDATA #IMPLIED>
  <!ATTLIST ROW DocumentFullPathAndName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentNumber CDATA #IMPLIED>
  <!ATTLIST ROW DrawnBy CDATA #IMPLIED>
  <!ATTLIST ROW Engineer CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Height_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Height_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Ibis_Model CDATA #IMPLIED>
  <!ATTLIST ROW ImagePath CDATA #IMPLIED>
  <!ATTLIST ROW Index CDATA #IMPLIED>
  <!ATTLIST ROW ItemGUID CDATA #IMPLIED>
  <!ATTLIST ROW Library_Name CDATA #IMPLIED>
  <!ATTLIST ROW Library_Reference CDATA #IMPLIED>
  <!ATTLIST ROW LibRef CDATA #IMPLIED>
  <!ATTLIST ROW LogicalDesignator CDATA #IMPLIED>
  <!ATTLIST ROW Model_Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Models CDATA #IMPLIED>
  <!ATTLIST ROW ModifiedDate CDATA #IMPLIED>
  <!ATTLIST ROW Organization CDATA #IMPLIED>
  <!ATTLIST ROW PartType CDATA #IMPLIED>
  <!ATTLIST ROW PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW PhysicalPath CDATA #IMPLIED>
  <!ATTLIST ROW Pins CDATA #IMPLIED>
  <!ATTLIST ROW Project CDATA #IMPLIED>
  <!ATTLIST ROW ProjectName CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Revision CDATA #IMPLIED>
  <!ATTLIST ROW RevisionGUID CDATA #IMPLIED>
  <!ATTLIST ROW Rule CDATA #IMPLIED>
  <!ATTLIST ROW SheetNumber CDATA #IMPLIED>
  <!ATTLIST ROW SheetTotal CDATA #IMPLIED>
  <!ATTLIST ROW Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Simulation CDATA #IMPLIED>
  <!ATTLIST ROW SourceLibraryName CDATA #IMPLIED>
  <!ATTLIST ROW Sub_Parts CDATA #IMPLIED>
  <!ATTLIST ROW Time CDATA #IMPLIED>
  <!ATTLIST ROW Title CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdName CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdPath CDATA #IMPLIED>
  <!ATTLIST ROW Variant CDATA #IMPLIED>
  <!ATTLIST ROW VaultGUID CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Address1" Caption="Address1" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Address2" Caption="Address2" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Address3" Caption="Address3" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Address4" Caption="Address4" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy" Caption="ApprovedBy" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="Author" Caption="Author" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="CheckedBy" Caption="CheckedBy" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="CompanyName" Caption="CompanyName" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="Component_Kind" Caption="Component Kind" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="ComponentKind" Caption="ComponentKind" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="CurrentDate" Caption="CurrentDate" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="CurrentTime" Caption="CurrentTime" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="Date" Caption="Date" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_Mil_" Caption="Designator-X&#40;Mil&#41;" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_mm_" Caption="Designator-X&#40;mm&#41;" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_Mil_" Caption="Designator-Y&#40;Mil&#41;" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_mm_" Caption="Designator-Y&#40;mm&#41;" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
    <COLUMN Name="DesignItemId" Caption="DesignItemId" Index="20" BandIndex="0" RowIndex="0" ColIndex="20" Width="100"></COLUMN>
    <COLUMN Name="Document" Caption="Document" Index="21" BandIndex="0" RowIndex="0" ColIndex="21" Width="100"></COLUMN>
    <COLUMN Name="DocumentFullPathAndName" Caption="DocumentFullPathAndName" Index="22" BandIndex="0" RowIndex="0" ColIndex="22" Width="100"></COLUMN>
    <COLUMN Name="DocumentName" Caption="DocumentName" Index="23" BandIndex="0" RowIndex="0" ColIndex="23" Width="100"></COLUMN>
    <COLUMN Name="DocumentNumber" Caption="DocumentNumber" Index="24" BandIndex="0" RowIndex="0" ColIndex="24" Width="100"></COLUMN>
    <COLUMN Name="DrawnBy" Caption="DrawnBy" Index="25" BandIndex="0" RowIndex="0" ColIndex="25" Width="100"></COLUMN>
    <COLUMN Name="Engineer" Caption="Engineer" Index="26" BandIndex="0" RowIndex="0" ColIndex="26" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="27" BandIndex="0" RowIndex="0" ColIndex="27" Width="100"></COLUMN>
    <COLUMN Name="Height_Mil_" Caption="Height&#40;Mil&#41;" Index="28" BandIndex="0" RowIndex="0" ColIndex="28" Width="100"></COLUMN>
    <COLUMN Name="Height_mm_" Caption="Height&#40;mm&#41;" Index="29" BandIndex="0" RowIndex="0" ColIndex="29" Width="100"></COLUMN>
    <COLUMN Name="Ibis_Model" Caption="Ibis Model" Index="30" BandIndex="0" RowIndex="0" ColIndex="30" Width="100"></COLUMN>
    <COLUMN Name="ImagePath" Caption="ImagePath" Index="31" BandIndex="0" RowIndex="0" ColIndex="31" Width="100"></COLUMN>
    <COLUMN Name="Index" Caption="Index" Index="32" BandIndex="0" RowIndex="0" ColIndex="32" Width="100"></COLUMN>
    <COLUMN Name="ItemGUID" Caption="ItemGUID" Index="33" BandIndex="0" RowIndex="0" ColIndex="33" Width="100"></COLUMN>
    <COLUMN Name="Library_Name" Caption="Library Name" Index="34" BandIndex="0" RowIndex="0" ColIndex="34" Width="100"></COLUMN>
    <COLUMN Name="Library_Reference" Caption="Library Reference" Index="35" BandIndex="0" RowIndex="0" ColIndex="35" Width="100"></COLUMN>
    <COLUMN Name="LibRef" Caption="LibRef" Index="36" BandIndex="0" RowIndex="0" ColIndex="36" Width="100"></COLUMN>
    <COLUMN Name="LogicalDesignator" Caption="LogicalDesignator" Index="37" BandIndex="0" RowIndex="0" ColIndex="37" Width="100"></COLUMN>
    <COLUMN Name="Model_Footprint" Caption="Model:Footprint" Index="38" BandIndex="0" RowIndex="0" ColIndex="38" Width="100"></COLUMN>
    <COLUMN Name="Models" Caption="Models" Index="39" BandIndex="0" RowIndex="0" ColIndex="39" Width="100"></COLUMN>
    <COLUMN Name="ModifiedDate" Caption="ModifiedDate" Index="40" BandIndex="0" RowIndex="0" ColIndex="40" Width="100"></COLUMN>
    <COLUMN Name="Organization" Caption="Organization" Index="41" BandIndex="0" RowIndex="0" ColIndex="41" Width="100"></COLUMN>
    <COLUMN Name="PartType" Caption="PartType" Index="42" BandIndex="0" RowIndex="0" ColIndex="42" Width="100"></COLUMN>
    <COLUMN Name="PCB3D" Caption="PCB3D" Index="43" BandIndex="0" RowIndex="0" ColIndex="43" Width="100"></COLUMN>
    <COLUMN Name="PhysicalPath" Caption="PhysicalPath" Index="44" BandIndex="0" RowIndex="0" ColIndex="44" Width="100"></COLUMN>
    <COLUMN Name="Pins" Caption="Pins" Index="45" BandIndex="0" RowIndex="0" ColIndex="45" Width="100"></COLUMN>
    <COLUMN Name="Project" Caption="Project" Index="46" BandIndex="0" RowIndex="0" ColIndex="46" Width="100"></COLUMN>
    <COLUMN Name="ProjectName" Caption="ProjectName" Index="47" BandIndex="0" RowIndex="0" ColIndex="47" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="48" BandIndex="0" RowIndex="0" ColIndex="48" Width="100"></COLUMN>
    <COLUMN Name="Revision" Caption="Revision" Index="49" BandIndex="0" RowIndex="0" ColIndex="49" Width="100"></COLUMN>
    <COLUMN Name="RevisionGUID" Caption="RevisionGUID" Index="50" BandIndex="0" RowIndex="0" ColIndex="50" Width="100"></COLUMN>
    <COLUMN Name="Rule" Caption="Rule" Index="51" BandIndex="0" RowIndex="0" ColIndex="51" Width="100"></COLUMN>
    <COLUMN Name="SheetNumber" Caption="SheetNumber" Index="52" BandIndex="0" RowIndex="0" ColIndex="52" Width="100"></COLUMN>
    <COLUMN Name="SheetTotal" Caption="SheetTotal" Index="53" BandIndex="0" RowIndex="0" ColIndex="53" Width="100"></COLUMN>
    <COLUMN Name="Signal_Integrity" Caption="Signal Integrity" Index="54" BandIndex="0" RowIndex="0" ColIndex="54" Width="100"></COLUMN>
    <COLUMN Name="Simulation" Caption="Simulation" Index="55" BandIndex="0" RowIndex="0" ColIndex="55" Width="100"></COLUMN>
    <COLUMN Name="SourceLibraryName" Caption="SourceLibraryName" Index="56" BandIndex="0" RowIndex="0" ColIndex="56" Width="100"></COLUMN>
    <COLUMN Name="Sub_Parts" Caption="Sub-Parts" Index="57" BandIndex="0" RowIndex="0" ColIndex="57" Width="100"></COLUMN>
    <COLUMN Name="Time" Caption="Time" Index="58" BandIndex="0" RowIndex="0" ColIndex="58" Width="100"></COLUMN>
    <COLUMN Name="Title" Caption="Title" Index="59" BandIndex="0" RowIndex="0" ColIndex="59" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdName" Caption="UniqueIdName" Index="60" BandIndex="0" RowIndex="0" ColIndex="60" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdPath" Caption="UniqueIdPath" Index="61" BandIndex="0" RowIndex="0" ColIndex="61" Width="100"></COLUMN>
    <COLUMN Name="Variant" Caption="Variant" Index="62" BandIndex="0" RowIndex="0" ColIndex="62" Width="100"></COLUMN>
    <COLUMN Name="VaultGUID" Caption="VaultGUID" Index="63" BandIndex="0" RowIndex="0" ColIndex="63" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="" CheckedBy="" Comment="TMS320VC5402" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2015/6/16" CurrentTime="0:15:18" Date="" Description="TMS320VC5402" Designator="U&#63;" Designator_X_Mil_="3598.662" Designator_X_mm_="91.406" Designator_Y_Mil_="5721.811" Designator_Y_mm_="145.334" DesignItemId="TMS320VC5402" Document="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;PART2_PowerSupply.SchDoc" DocumentFullPathAndName="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;PART2_PowerSupply.SchDoc" DocumentName="PART2_PowerSupply.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="TMS320VC5401_PQFP144" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="4" ItemGUID="" Library_Name="TMS320VC5401.SchLib" Library_Reference="TMS320VC5402" LibRef="TMS320VC5402" LogicalDesignator="U&#63;" Model_Footprint="TSQFP, 144-Leads, Body 20.00x20.00mm, Pitch 0.50mm, IPC Medium Density" Models="1" ModifiedDate="2015/6/16" Organization="" PartType="TMS320VC5402" PCB3D="" PhysicalPath="PART2_PowerSupply" Pins="144" Project="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;C5402AudioSystem.PrjPCB" ProjectName="C5402AudioSystem.PrjPCB" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="" Signal_Integrity="" Simulation="" SourceLibraryName="TMS320VC5401.SchLib" Sub_Parts="1" Time="" Title="" UniqueIdName="SFBVXVPV" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="" CheckedBy="" Comment="TMS320VC5402" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2015/6/16" CurrentTime="0:15:19" Date="" Description="TMS320VC5402" Designator="U&#63;" Designator_X_Mil_="4817.559" Designator_X_mm_="122.366" Designator_Y_Mil_="5740.158" Designator_Y_mm_="145.8" DesignItemId="TMS320VC5402" Document="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;PART4_Basic.SchDoc" DocumentFullPathAndName="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;PART4_Basic.SchDoc" DocumentName="PART4_Basic.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="TMS320VC5401_PQFP144" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="2" ItemGUID="" Library_Name="TMS320VC5401.SchLib" Library_Reference="TMS320VC5402" LibRef="TMS320VC5402" LogicalDesignator="U&#63;" Model_Footprint="TSQFP, 144-Leads, Body 20.00x20.00mm, Pitch 0.50mm, IPC Medium Density" Models="1" ModifiedDate="2015/6/16" Organization="" PartType="TMS320VC5402" PCB3D="" PhysicalPath="PART4_Basic" Pins="144" Project="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;C5402AudioSystem.PrjPCB" ProjectName="C5402AudioSystem.PrjPCB" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="" Signal_Integrity="" Simulation="" SourceLibraryName="TMS320VC5401.SchLib" Sub_Parts="1" Time="" Title="" UniqueIdName="CVSXOJMT" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="" CheckedBy="" Comment="TMS320VC5402" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2015/6/16" CurrentTime="0:15:19" Date="" Description="TMS320VC5402" Designator="U&#63;" Designator_X_Mil_="4979.764" Designator_X_mm_="126.486" Designator_Y_Mil_="6318.11" Designator_Y_mm_="160.48" DesignItemId="TMS320VC5402" Document="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;PART3_Memory.SchDoc" DocumentFullPathAndName="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;PART3_Memory.SchDoc" DocumentName="PART3_Memory.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="TMS320VC5401_PQFP144" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="3" ItemGUID="" Library_Name="TMS320VC5401.SchLib" Library_Reference="TMS320VC5402" LibRef="TMS320VC5402" LogicalDesignator="U&#63;" Model_Footprint="TSQFP, 144-Leads, Body 20.00x20.00mm, Pitch 0.50mm, IPC Medium Density" Models="1" ModifiedDate="2015/6/16" Organization="" PartType="TMS320VC5402" PCB3D="" PhysicalPath="PART3_Memory" Pins="144" Project="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;C5402AudioSystem.PrjPCB" ProjectName="C5402AudioSystem.PrjPCB" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="" Signal_Integrity="" Simulation="" SourceLibraryName="TMS320VC5401.SchLib" Sub_Parts="1" Time="" Title="" UniqueIdName="OKFWMYBR" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="" CheckedBy="" Comment="TMS320VC5402" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2015/6/16" CurrentTime="0:15:19" Date="" Description="TMS320VC5402" Designator="U&#63;" Designator_X_Mil_="5211.26" Designator_X_mm_="132.366" Designator_Y_Mil_="5618.11" Designator_Y_mm_="142.7" DesignItemId="TMS320VC5402" Document="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;PART5_HPI_McBSP.SchDoc" DocumentFullPathAndName="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;PART5_HPI_McBSP.SchDoc" DocumentName="PART5_HPI_McBSP.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="TMS320VC5401_PQFP144" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="1" ItemGUID="" Library_Name="TMS320VC5401.SchLib" Library_Reference="TMS320VC5402" LibRef="TMS320VC5402" LogicalDesignator="U&#63;" Model_Footprint="TSQFP, 144-Leads, Body 20.00x20.00mm, Pitch 0.50mm, IPC Medium Density" Models="1" ModifiedDate="2015/6/16" Organization="" PartType="TMS320VC5402" PCB3D="" PhysicalPath="PART5_HPI_McBSP" Pins="144" Project="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;C5402AudioSystem.PrjPCB" ProjectName="C5402AudioSystem.PrjPCB" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="" Signal_Integrity="" Simulation="" SourceLibraryName="TMS320VC5401.SchLib" Sub_Parts="1" Time="" Title="" UniqueIdName="VGDPFKGV" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="&#23828; &#25942;; &#26446;&#23578;&#25991;" CheckedBy="" Comment="TMS320VC5402" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2015/6/16" CurrentTime="0:15:18" Date="" Description="TMS320VC5402" Designator="U&#63;" Designator_X_Mil_="5400" Designator_X_mm_="137.16" Designator_Y_Mil_="4000" Designator_Y_mm_="101.6" DesignItemId="TMS320VC5402" Document="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;PART1_NC.SchDoc" DocumentFullPathAndName="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;PART1_NC.SchDoc" DocumentName="PART1_NC.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="TMS320VC5401_PQFP144" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="5" ItemGUID="" Library_Name="TMS320VC5401.SchLib" Library_Reference="TMS320VC5402" LibRef="TMS320VC5402" LogicalDesignator="U&#63;" Model_Footprint="TSQFP, 144-Leads, Body 20.00x20.00mm, Pitch 0.50mm, IPC Medium Density" Models="1" ModifiedDate="2015/6/16" Organization="" PartType="TMS320VC5402" PCB3D="" PhysicalPath="PART1_NC" Pins="144" Project="f:&#92;Leo&#92;Documents&#92;Altium&#92;Projects&#92;C5402 Audio System&#92;C5402AudioSystem.PrjPCB" ProjectName="C5402AudioSystem.PrjPCB" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="1" SheetTotal="5" Signal_Integrity="" Simulation="" SourceLibraryName="TMS320VC5401.SchLib" Sub_Parts="1" Time="" Title="&#38750;&#36830;&#25509;&#20214;" UniqueIdName="BNNIAHQX" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
  </ROWS>
</GRID>
